sudo : required
services :
    - docker
before_install : 
    - docker build -t sandipansahana/my-docker-test -f Dockerfile.dev .

script :
    - docker run sandipansahana/my-docker-test npm run test -- --coverage
    
deploy :
    provider : elasticbeanstalk
    region : "eu-west-2"
    app : "dock"
    env : "Dock-env"
    bucket_name : "elasticbeanstalk-eu-west-2-050418195270"
    bucket_path : "dock"
    on :
        branch : master
    access_key_id : $AWS_ACCESS_KEY
    secret_access_key :
        secure : "$AWS_SECRET_KEY"