sudo : required
services :
    - docker
before_install : 
    - docker build -t sandipansahana/my-docker-test -f Dockerfile.dev .

script :
    - docker run sandipansahana/my-docker-test npm run test -- --coverage