version : '3'
services :
    web : 
        build : 
            context : .
            dockerfile : Dockerfile.dev
        ports :
            - "3000:3000"
        volumes :
            - /app/myApp/node_modules
            - .:/app/myApp
    tests :
        build : 
            context : .
            dockerfile : Dockerfile.dev
        volumes :
            - /app/myApp/node_modules
            - .:/app/myApp
        command : ["npm", "run", "test"]
            